### ISSUE TITLE
some colorscheme can fallback

### ISSUE THREAD

**Issue by cipherlogs** [mcchrish/vim-no-color-collections#19]
Hello,

A color scheme like
https://github.com/lifepillar/vim-gruvbox8
https://github.com/lifepillar/vim-solarized8

they can fallback to 2colors, and it makes them very minimal and not distracting at all

I have tried to use them in that mode, but still can't figure out how https://www.reddit.com/r/vim/comments/nlmrrj/cant_figure_out_how_to_get_this_color_scheme/

you might know how to do it.

if so please share how
and maybe add them to the list because some would appreciate using known colorschemes and make them go from minimal to normal as they wish 

Thank you!

**Comment by mcchrish** [comment]
Wow that color scheme graceful degrade is quite clever honestly. I'm fine for them to be added but we probably have to include instructions how to achieve those minimal colors or just a link to the instructions / README section. A PR is welcome.
